runtime: python39
entrypoint: python main.py

env_variables:
  FLASK_ENV: production
  # Add your OPENAI_API_KEY here:
  # OPENAI_API_KEY: "your-openai-api-key-here"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto