steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mymedsmateai', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mymedsmateai']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'mymedsmateai'
  - '--image'
  - 'gcr.io/$PROJECT_ID/mymedsmateai'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
substitutions:
  _OPENAI_API_KEY: 'your-openai-api-key-here'